export const PREMIUM_LIVE_HOTELS = [
  {
    key: 'blue-waters',
    label: 'Blue Waters Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Blue Waters Hotel'],
  },
  {
    key: 'garden-court-south-beach',
    label: 'Garden Court South Beach',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Garden Court South Beach', 'Southern Sun Garden Court South Beach'],
  },
  {
    key: 'the-edward',
    label: 'The Edward',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['The Edward', 'Southern Sun The Edward'],
  },
  {
    key: 'the-balmoral',
    label: 'The Balmoral',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['The Balmoral'],
  },
  {
    key: 'belaire-suites-hotel',
    label: 'Belaire Suites Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Belaire Suites Hotel'],
  },
  {
    key: 'gooderson-tropicana-hotel',
    label: 'Gooderson Tropicana Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Gooderson Tropicana Hotel'],
  },
  {
    key: 'gooderson-leisure-silver-sands-2',
    label: 'Gooderson Leisure Silver Sands 2',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Gooderson Leisure Silver Sands 2'],
  },
  {
    key: 'first-group-the-palace-all-suite',
    label: 'First Group The Palace All-Suite',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['First Group The Palace All-Suite'],
  },
  {
    key: 'garden-court-marine-parade',
    label: 'Garden Court Marine Parade',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Garden Court Marine Parade', 'Southern Sun Garden Court Marine Parade'],
  },
  {
    key: 'southern-sun-elangeni-maharani',
    label: 'Southern Sun Elangeni & Maharani Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Southern Sun Elangeni & Maharani Hotel', 'Southern Sun Elangeni & Maharani'],
  },
  {
    key: 'suncoast-hotel-towers',
    label: 'Suncoast Hotel & Towers',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Suncoast Hotel & Towers'],
  },
  {
    key: 'sea-esta-luxury-apartment-107',
    label: 'Sea Esta Luxury Apartment 107',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Sea Esta Luxury Apartment 107'],
  },
  {
    key: 'beach-hurst-303',
    label: 'Beach Hurst 303',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Beach Hurst 303'],
  },
  {
    key: 'ushaka-views',
    label: 'UshakaViews',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['UshakaViews'],
  },
  {
    key: 'indlovukazi-guesthouse',
    label: 'Indlovukazi Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Indlovukazi Guesthouse'],
  },
  {
    key: 'villa-paradiso-hotel',
    label: 'Villa Paradiso Hotel',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Villa Paradiso Hotel'],
  },
  {
    key: 'cocomo-boutique-hotel',
    label: 'Cocomo Boutique Hotel',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Cocomo Boutique Hotel'],
  },
  {
    key: 'the-riverleaf-hotel',
    label: 'The Riverleaf Hotel',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['The Riverleaf Hotel'],
  },
  {
    key: 'kosmos-manor',
    label: 'Kosmos Manor',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Kosmos Manor'],
  },
  {
    key: 'palm-swift-luxury',
    label: 'Palm Swift Luxury',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Palm Swift Luxury'],
  },
  {
    key: 'the-venue-country-hotel-and-spa',
    label: 'The Venue Country Hotel and Spa',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['The Venue Country Hotel and Spa'],
  },
  {
    key: 'waterfront-guesthouse',
    label: 'Waterfront Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Waterfront Guesthouse'],
  },
  {
    key: 'metsingat-harties',
    label: 'MetsingAt Harties',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['MetsingAt Harties'],
  },
  {
    key: 'marina-view-guesthouse',
    label: 'Marina View Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Marina View Guesthouse'],
  },
  {
    key: 'cozy-kosmos',
    label: 'Cozy Kosmos',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Cozy Kosmos'],
  },
  {
    key: 'serenity-guesthouse',
    label: 'Serenity Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Serenity Guesthouse'],
  },
  {
    key: 'mint-hotel-the-blyde',
    label: 'Mint Hotel The Blyde',
    destination: 'pretoria',
    destinationLabel: 'Pretoria',
    aliases: ['Mint Hotel The Blyde'],
  },
  {
    key: 'blyde-penthouse-apartments',
    label: 'Blyde Penthouse Apartments',
    destination: 'pretoria',
    destinationLabel: 'Pretoria',
    aliases: ['Blyde Penthouse Apartments'],
  },
  {
    key: 'sea-point-apartment',
    label: 'Sea Point Apartment',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Sea Point Apartment'],
  },
  {
    key: 'bantry-aparthotel-totalstay',
    label: 'The Bantry Aparthotel by Totalstay',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['The Bantry Aparthotel by Totalstay'],
  },
  {
    key: 'casa-on-kei-totalstay',
    label: 'Casa on Kei by Totalstay',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Casa on Kei by Totalstay'],
  },
  {
    key: 'spring-tide-inn-ctha',
    label: 'Spring Tide Inn by CTHA',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Spring Tide Inn by CTHA'],
  },
  {
    key: 'first-group-riviera-suites',
    label: 'First Group Riviera Suites',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['First Group Riviera Suites'],
  },
  {
    key: 'home-suite-hotels-sea-point',
    label: 'Home Suite Hotels Sea Point',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Home Suite Hotels Sea Point', 'Home Suite Hotels'],
  },
  {
    key: 'camps-bay-village',
    label: 'Camps Bay Village',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Village'],
  },
  {
    key: '3-on-camps-bay',
    label: '3 On Camps Bay',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['3 On Camps Bay'],
  },
  {
    key: 'camps-bay-beach-front-apartment',
    label: 'Camps Bay Beach Front Apartment',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Beach Front Apartment'],
  },
  {
    key: 'camps-bay-private-room',
    label: 'Camps Bay Private Room',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Private Room', 'Camps Bay private room and bathroom'],
  },
  {
    key: 'camps-bay-studio',
    label: 'Camps Bay Studio',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Studio', 'Camps Bay Studio with private patio'],
  },
  {
    key: 'cape-diamond-boutique-hotel',
    label: 'Cape Diamond Boutique Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Cape Diamond Boutique Hotel'],
  },
  {
    key: 'fountains-hotel-cape-town',
    label: 'Fountains Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Fountains Hotel'],
  },
  {
    key: 'holiday-inn-express-cape-town',
    label: 'Holiday Inn Express Cape Town City Centre',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Holiday Inn Express Cape Town City Centre'],
  },
  {
    key: 'hotel-sky-cape-town',
    label: 'Hotel Sky Cape Town',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Hotel Sky Cape Town'],
  },
  {
    key: 'cresta-grande-cape-town',
    label: 'Cresta Grande Cape Town',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Cresta Grande Cape Town'],
  },
  {
    key: 'radisson-cape-town-foreshore',
    label: 'Radisson Hotel Cape Town Foreshore',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Radisson Hotel Cape Town Foreshore'],
  },
  {
    key: 'onomo-inn-on-the-square',
    label: 'ONOMO Hotel Cape Town Inn On The Square',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['ONOMO Hotel Cape Town Inn On The Square', 'ONOMO Hotel Cape Town – Inn On The Square'],
  },
  {
    key: 'onomo-hotel-foreshore',
    label: 'ONOMO Hotel Foreshore',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['ONOMO Hotel Foreshore'],
  },
  {
    key: 'first-beach-203-ctha',
    label: 'First Beach 203 by CTHA',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['First Beach 203 by CTHA'],
  },
  {
    key: 'clifton-yolo-spaces',
    label: 'Clifton YOLO Spaces',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Clifton YOLO Spaces'],
  },
  {
    key: 'radisson-red-va-waterfront',
    label: 'Radisson RED Hotel V&A Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Radisson RED Hotel V&A Waterfront Cape Town'],
  },
  {
    key: 'cape-grace-va-waterfront',
    label: 'Cape Grace V&A Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Cape Grace V&A Waterfront', 'Cape Grace, V&A Waterfront, A Fairmont Managed Hotel'],
  },
  {
    key: 'waterfront-village-va',
    label: 'Waterfront Village V&A Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Waterfront Village V&A Waterfront', 'Waterfront Village'],
  },
  {
    key: 'southern-sun-waterfront',
    label: 'Southern Sun Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Southern Sun Waterfront'],
  },
  {
    key: 'president-hotel-cape-town',
    label: 'President Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['President Hotel'],
  },
  {
    key: 'the-bay-hotel',
    label: 'The Bay Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['The Bay Hotel'],
  },
  {
    key: 'twelve-apostles-hotel-spa',
    label: 'Twelve Apostles Hotel & Spa',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Twelve Apostles Hotel & Spa'],
  },
  {
    key: 'protea-hotel-sea-point',
    label: 'Protea Hotel Sea Point',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Protea Hotel Sea Point'],
  },
  {
    key: 'the-marly-cape-town',
    label: 'The Marly',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['The Marly'],
  },
] as const;

export type PremiumLiveHotelKey = (typeof PREMIUM_LIVE_HOTELS)[number]['key'];
export type PremiumLiveHotelOption = (typeof PREMIUM_LIVE_HOTELS)[number];

const NAME_TO_KEY = new Map<string, PremiumLiveHotelKey>();

for (const hotel of PREMIUM_LIVE_HOTELS) {
  for (const alias of hotel.aliases) {
    NAME_TO_KEY.set(alias.trim().toLowerCase(), hotel.key);
  }
}

export function getPremiumLiveHotelKeyByName(name: string) {
  return NAME_TO_KEY.get(name.trim().toLowerCase()) ?? null;
}

export function getPremiumLiveHotelsByDestination(destination: string) {
  return PREMIUM_LIVE_HOTELS.filter((hotel) => hotel.destination === destination);
}
