export const PREMIUM_LIVE_HOTELS = [
  {
    key: 'blue-waters',
    label: 'Blue Waters Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Blue Waters Hotel'],
  },
  {
    key: 'garden-court-south-beach',
    label: 'Garden Court South Beach',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Garden Court South Beach', 'Southern Sun Garden Court South Beach'],
  },
  {
    key: 'the-edward',
    label: 'The Edward',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['The Edward', 'Southern Sun The Edward'],
  },
  {
    key: 'the-balmoral',
    label: 'The Balmoral',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['The Balmoral'],
  },
  {
    key: 'belaire-suites-hotel',
    label: 'Belaire Suites Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Belaire Suites Hotel'],
  },
  {
    key: 'gooderson-tropicana-hotel',
    label: 'Gooderson Tropicana Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Gooderson Tropicana Hotel'],
  },
  {
    key: 'gooderson-leisure-silver-sands-2',
    label: 'Gooderson Leisure Silver Sands 2',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Gooderson Leisure Silver Sands 2'],
  },
  {
    key: 'first-group-the-palace-all-suite',
    label: 'First Group The Palace All-Suite',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['First Group The Palace All-Suite'],
  },
  {
    key: 'garden-court-marine-parade',
    label: 'Garden Court Marine Parade',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Garden Court Marine Parade', 'Southern Sun Garden Court Marine Parade'],
  },
  {
    key: 'southern-sun-elangeni-maharani',
    label: 'Southern Sun Elangeni & Maharani Hotel',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Southern Sun Elangeni & Maharani Hotel', 'Southern Sun Elangeni & Maharani'],
  },
  {
    key: 'suncoast-hotel-towers',
    label: 'Suncoast Hotel & Towers',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Suncoast Hotel & Towers'],
  },
  {
    key: 'sea-esta-luxury-apartment-107',
    label: 'Sea Esta Luxury Apartment 107',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Sea Esta Luxury Apartment 107'],
  },
  {
    key: 'beach-hurst-303',
    label: 'Beach Hurst 303',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['Beach Hurst 303'],
  },
  {
    key: 'ushaka-views',
    label: 'UshakaViews',
    destination: 'durban',
    destinationLabel: 'Durban',
    aliases: ['UshakaViews'],
  },
  {
    key: 'indlovukazi-guesthouse',
    label: 'Indlovukazi Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Indlovukazi Guesthouse'],
  },
  {
    key: 'villa-paradiso-hotel',
    label: 'Villa Paradiso Hotel',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Villa Paradiso Hotel'],
  },
  {
    key: 'cocomo-boutique-hotel',
    label: 'Cocomo Boutique Hotel',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Cocomo Boutique Hotel'],
  },
  {
    key: 'the-riverleaf-hotel',
    label: 'The Riverleaf Hotel',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['The Riverleaf Hotel'],
  },
  {
    key: 'kosmos-manor',
    label: 'Kosmos Manor',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Kosmos Manor'],
  },
  {
    key: 'palm-swift-luxury',
    label: 'Palm Swift Luxury',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Palm Swift Luxury'],
  },
  {
    key: 'the-venue-country-hotel-and-spa',
    label: 'The Venue Country Hotel and Spa',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['The Venue Country Hotel and Spa'],
  },
  {
    key: 'waterfront-guesthouse',
    label: 'Waterfront Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Waterfront Guesthouse'],
  },
  {
    key: 'metsingat-harties',
    label: 'MetsingAt Harties',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['MetsingAt Harties'],
  },
  {
    key: 'marina-view-guesthouse',
    label: 'Marina View Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Marina View Guesthouse'],
  },
  {
    key: 'cozy-kosmos',
    label: 'Cozy Kosmos',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Cozy Kosmos'],
  },
  {
    key: 'serenity-guesthouse',
    label: 'Serenity Guesthouse',
    destination: 'harties',
    destinationLabel: 'Hartbeespoort',
    aliases: ['Serenity Guesthouse'],
  },
  {
    key: 'mint-hotel-the-blyde',
    label: 'Mint Hotel The Blyde',
    destination: 'pretoria',
    destinationLabel: 'Pretoria',
    aliases: ['Mint Hotel The Blyde'],
  },
  {
    key: 'blyde-penthouse-apartments',
    label: 'Blyde Penthouse Apartments',
    destination: 'pretoria',
    destinationLabel: 'Pretoria',
    aliases: ['Blyde Penthouse Apartments'],
  },
  {
    key: 'sea-point-apartment',
    label: 'Sea Point Apartment',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Sea Point Apartment'],
  },
  {
    key: 'bantry-aparthotel-totalstay',
    label: 'The Bantry Aparthotel by Totalstay',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['The Bantry Aparthotel by Totalstay'],
  },
  {
    key: 'casa-on-kei-totalstay',
    label: 'Casa on Kei by Totalstay',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Casa on Kei by Totalstay'],
  },
  {
    key: 'spring-tide-inn-ctha',
    label: 'Spring Tide Inn by CTHA',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Spring Tide Inn by CTHA'],
  },
  {
    key: 'first-group-riviera-suites',
    label: 'First Group Riviera Suites',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['First Group Riviera Suites'],
  },
  {
    key: 'home-suite-hotels-sea-point',
    label: 'Home Suite Hotels Sea Point',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Home Suite Hotels Sea Point', 'Home Suite Hotels'],
  },
  {
    key: 'camps-bay-village',
    label: 'Camps Bay Village',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Village'],
  },
  {
    key: '3-on-camps-bay',
    label: '3 On Camps Bay',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['3 On Camps Bay'],
  },
  {
    key: 'camps-bay-beach-front-apartment',
    label: 'Camps Bay Beach Front Apartment',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Beach Front Apartment'],
  },
  {
    key: 'camps-bay-private-room',
    label: 'Camps Bay Private Room',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Private Room', 'Camps Bay private room and bathroom'],
  },
  {
    key: 'camps-bay-studio',
    label: 'Camps Bay Studio',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Camps Bay Studio', 'Camps Bay Studio with private patio'],
  },
  {
    key: 'cape-diamond-boutique-hotel',
    label: 'Cape Diamond Boutique Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Cape Diamond Boutique Hotel'],
  },
  {
    key: 'fountains-hotel-cape-town',
    label: 'Fountains Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Fountains Hotel'],
  },
  {
    key: 'holiday-inn-express-cape-town',
    label: 'Holiday Inn Express Cape Town City Centre',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Holiday Inn Express Cape Town City Centre'],
  },
  {
    key: 'hotel-sky-cape-town',
    label: 'Hotel Sky Cape Town',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Hotel Sky Cape Town'],
  },
  {
    key: 'cresta-grande-cape-town',
    label: 'Cresta Grande Cape Town',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Cresta Grande Cape Town'],
  },
  {
    key: 'radisson-cape-town-foreshore',
    label: 'Radisson Hotel Cape Town Foreshore',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Radisson Hotel Cape Town Foreshore'],
  },
  {
    key: 'onomo-inn-on-the-square',
    label: 'ONOMO Hotel Cape Town Inn On The Square',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['ONOMO Hotel Cape Town Inn On The Square', 'ONOMO Hotel Cape Town – Inn On The Square'],
  },
  {
    key: 'onomo-hotel-foreshore',
    label: 'ONOMO Hotel Foreshore',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['ONOMO Hotel Foreshore'],
  },
  {
    key: 'first-beach-203-ctha',
    label: 'First Beach 203 by CTHA',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['First Beach 203 by CTHA'],
  },
  {
    key: 'clifton-yolo-spaces',
    label: 'Clifton YOLO Spaces',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Clifton YOLO Spaces'],
  },
  {
    key: 'radisson-red-va-waterfront',
    label: 'Radisson RED Hotel V&A Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Radisson RED Hotel V&A Waterfront Cape Town'],
  },
  {
    key: 'cape-grace-va-waterfront',
    label: 'Cape Grace V&A Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Cape Grace V&A Waterfront', 'Cape Grace, V&A Waterfront, A Fairmont Managed Hotel'],
  },
  {
    key: 'waterfront-village-va',
    label: 'Waterfront Village V&A Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Waterfront Village V&A Waterfront', 'Waterfront Village'],
  },
  {
    key: 'southern-sun-waterfront',
    label: 'Southern Sun Waterfront',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Southern Sun Waterfront'],
  },
  {
    key: 'president-hotel-cape-town',
    label: 'President Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['President Hotel'],
  },
  {
    key: 'the-bay-hotel',
    label: 'The Bay Hotel',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['The Bay Hotel'],
  },
  {
    key: 'twelve-apostles-hotel-spa',
    label: 'Twelve Apostles Hotel & Spa',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Twelve Apostles Hotel & Spa'],
  },
  {
    key: 'protea-hotel-sea-point',
    label: 'Protea Hotel Sea Point',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['Protea Hotel Sea Point'],
  },
  {
    key: 'the-marly-cape-town',
    label: 'The Marly',
    destination: 'cape-town',
    destinationLabel: 'Cape Town',
    aliases: ['The Marly'],
  },
  {
    key: 'breakers-resort-apartments',
    label: 'Breakers Resort Apartments',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Breakers Resort Apartments'],
  },
  {
    key: 'aha-gateway-hotel-umhlanga',
    label: 'aha Gateway Hotel Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['aha Gateway Hotel Umhlanga'],
  },
  {
    key: 'the-villa-umhlanga',
    label: 'The Villa Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['The Villa Umhlanga'],
  },
  {
    key: 'protea-hotel-durban-umhlanga',
    label: 'Protea Hotel by Marriott Durban Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Protea Hotel by Marriott Durban Umhlanga'],
  },
  {
    key: 'holiday-inn-express-umhlanga',
    label: 'Holiday Inn Express Durban Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Holiday Inn Express Durban Umhlanga', 'Holiday Inn Express Durban - Umhlanga by IHG'],
  },
  {
    key: 'hilton-garden-inn-umhlanga',
    label: 'Hilton Garden Inn Umhlanga Arch',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Hilton Garden Inn Umhlanga Arch'],
  },
  {
    key: 'premier-splendid-inn-umhlanga',
    label: 'Premier Splendid Inn Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Premier Splendid Inn Umhlanga'],
  },
  {
    key: 'first-group-breakers-resort',
    label: 'First Group Breakers Resort',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['First Group Breakers Resort', 'First Group Breakers Resort - Official'],
  },
  {
    key: 'royal-palm-hotel-umhlanga',
    label: 'Royal Palm Hotel',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Royal Palm Hotel'],
  },
  {
    key: 'regal-inn-umhlanga-gateway',
    label: 'Regal Inn Umhlanga Gateway',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Regal Inn Umhlanga Gateway'],
  },
  {
    key: 'premier-hotel-umhlanga',
    label: 'Premier Hotel Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Premier Hotel Umhlanga'],
  },
  {
    key: 'radisson-blu-durban-umhlanga',
    label: 'Radisson Blu Hotel Durban Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Radisson Blu Hotel Durban Umhlanga', 'Radisson Blu Hotel, Durban Umhlanga'],
  },
  {
    key: 'the-millennial-umhlanga',
    label: 'The Millennial Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['The Millennial Umhlanga'],
  },
  {
    key: 'breakers-resort-232',
    label: 'Breakers Resort 232',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Breakers Resort 232', 'Breakers Resort, Umhlanga, 232'],
  },
  {
    key: 'oceans-apartments-radisson-blu',
    label: 'Oceans Apartments Balcony Suites Radisson Blu',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Oceans Apartments Balcony Suites Radisson Blu', 'Oceans Apartments Balcony Suites in the Radisson Blu Hotel Building Tower,Durban,Umhlanga'],
  },
  {
    key: 'town-lodge-umhlanga',
    label: 'Town Lodge Umhlanga',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['Town Lodge Umhlanga'],
  },
  {
    key: '71-sea-lodge-beachfront',
    label: '71 Sea Lodge Beachfront Apartment',
    destination: 'umhlanga',
    destinationLabel: 'Umhlanga',
    aliases: ['71 Sea Lodge Beachfront Apartment'],
  },
  {
    key: 'bakubung-bush-lodge',
    label: 'Bakubung Bush Lodge',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Bakubung Bush Lodge'],
  },
  {
    key: 'the-kingdom-resort',
    label: 'The Kingdom Resort',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['The Kingdom Resort'],
  },
  {
    key: 'kwa-maritane-lodge',
    label: 'Kwa Maritane Lodge',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Kwa Maritane Lodge'],
  },
  {
    key: 'sundown-country-estate',
    label: 'Sundown Country Estate',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Sundown Country Estate'],
  },
  {
    key: 'gettys-bed-and-breakfast',
    label: "Getty's Bed and Breakfast",
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ["Getty's Bed and Breakfast"],
  },
  {
    key: 'valley-view-guest-house',
    label: 'Valley View Guest House',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Valley View Guest House'],
  },
  {
    key: 'ivory-tree-game-lodge',
    label: 'Ivory Tree Game Lodge',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Ivory Tree Game Lodge'],
  },
  {
    key: 'pilanesberg-hotel',
    label: 'Pilanesberg Hotel',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Pilanesberg Hotel'],
  },
  {
    key: 'kedar-heritage-lodge',
    label: 'Kedar Heritage Lodge Conference Centre & Spa',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Kedar Heritage Lodge Conference Centre & Spa', 'Kedar Heritage Lodge, Conference Centre & Spa'],
  },
  {
    key: 'royal-marang-hotel',
    label: 'Royal Marang Hotel',
    destination: 'sun-city',
    destinationLabel: 'Sun City',
    aliases: ['Royal Marang Hotel'],
  },
  {
    key: 'the-russel-hotel',
    label: 'The Russel Hotel',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['The Russel Hotel'],
  },
  {
    key: 'knysna-log-inn-hotel',
    label: 'Knysna Log-Inn Hotel',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Knysna Log-Inn Hotel'],
  },
  {
    key: 'aha-the-rex-hotel',
    label: 'aha The Rex Hotel',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['aha The Rex Hotel'],
  },
  {
    key: 'protea-hotel-knysna-quays',
    label: 'Protea Hotel by Marriott Knysna Quays',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Protea Hotel by Marriott Knysna Quays'],
  },
  {
    key: 'th39-thesen-islands',
    label: 'TH39 Thesen Islands',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['TH39 Thesen Islands'],
  },
  {
    key: 'belle-view-knysna-quays',
    label: 'Belle View @ Knysna Quays',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Belle View @ Knysna Quays'],
  },
  {
    key: 'knysna-inn',
    label: 'Knysna Inn',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Knysna Inn'],
  },
  {
    key: 'gem-quays-waterfront',
    label: 'Gem Quays Waterfront',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Gem Quays Waterfront'],
  },
  {
    key: 'amazing-views-knysna',
    label: 'Amazing Views, Comfortable living space, Knysna',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Amazing Views, Comfortable living space, Knysna'],
  },
  {
    key: 'knysna-quays-4',
    label: 'KnysnaQuays 4',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['KnysnaQuays 4'],
  },
  {
    key: 'waterfront-apartment-knysna',
    label: 'Waterfront Apartment, Waterfront',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Waterfront Apartment, Waterfront'],
  },
  {
    key: 'knysna-houseboats',
    label: 'Knysna Houseboats',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Knysna Houseboats'],
  },
  {
    key: 'spinnaker-quays-waterfront-villa',
    label: 'Spinnaker Quays Waterfront Villa',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Spinnaker Quays Waterfront Villa'],
  },
  {
    key: 'phoenix-lodge-waterside',
    label: 'Phoenix Lodge and Waterside Accommodation',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Phoenix Lodge and Waterside Accommodation'],
  },
  {
    key: 'pezula-golf-estate-knysna',
    label: 'Knysna, Pezula Golf Estate',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Knysna, Pezula Golf Estate'],
  },
  {
    key: 'issaquena-heights-boutique-hotel',
    label: 'Issaquena Heights Boutique Hotel',
    destination: 'knysna',
    destinationLabel: 'Knysna',
    aliases: ['Issaquena Heights Boutique Hotel'],
  },
] as const;

export type PremiumLiveHotelKey = (typeof PREMIUM_LIVE_HOTELS)[number]['key'];
export type PremiumLiveHotelOption = (typeof PREMIUM_LIVE_HOTELS)[number];

const NAME_TO_KEY = new Map<string, PremiumLiveHotelKey>();

for (const hotel of PREMIUM_LIVE_HOTELS) {
  for (const alias of hotel.aliases) {
    NAME_TO_KEY.set(alias.trim().toLowerCase(), hotel.key);
  }
}

export function getPremiumLiveHotelKeyByName(name: string) {
  return NAME_TO_KEY.get(name.trim().toLowerCase()) ?? null;
}

export function getPremiumLiveHotelsByDestination(destination: string) {
  return PREMIUM_LIVE_HOTELS.filter((hotel) => hotel.destination === destination);
}
