import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Upload, FileText, Loader2, X } from 'lucide-react';
import { toast } from 'sonner';
import { extractQuoteDataFromPDF, QuoteFormData } from '@/lib/pdfQuoteUtils';

interface PDFQuoteUploaderProps {
  onQuoteLoaded: (data: QuoteFormData) => void;
  expectedQuoteType?: QuoteFormData['quoteType'];
}

export function PDFQuoteUploader({ onQuoteLoaded, expectedQuoteType }: PDFQuoteUploaderProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.type !== 'application/pdf') {
        toast.error('Please select a PDF file');
        return;
      }
      setSelectedFile(file);
    }
  };

  const handleLoadQuote = async () => {
    if (!selectedFile) {
      toast.error('Please select a PDF file first');
      return;
    }

    setIsLoading(true);
    try {
      const data = await extractQuoteDataFromPDF(selectedFile);
      
      if (!data) {
        toast.error('Could not extract quote data from this PDF. Please ensure it was generated by our system.');
        return;
      }

      // Validate quote type if specified
      if (expectedQuoteType && data.quoteType !== expectedQuoteType) {
        toast.warning(`This quote was created in a different section. Some fields may not load correctly.`);
      }

      onQuoteLoaded(data);
      toast.success('Quote loaded successfully! Review the form and make your changes.');
      
      // Clear the file input
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    } catch (error) {
      console.error('Error loading quote:', error);
      toast.error('Failed to load quote from PDF');
    } finally {
      setIsLoading(false);
    }
  };

  const handleClear = () => {
    setSelectedFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 rounded-xl p-4 mb-6">
      <div className="flex items-center gap-2 mb-3">
        <FileText className="w-5 h-5 text-amber-600" />
        <h3 className="font-semibold text-amber-900">Edit Existing Quote</h3>
      </div>
      <p className="text-sm text-amber-700 mb-4">
        Upload a previously generated PDF quote to edit it. The form fields will be populated with the quote data.
      </p>
      
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="flex-1">
          <Label htmlFor="pdf-upload" className="sr-only">Upload PDF Quote</Label>
          <div className="relative">
            <Input
              ref={fileInputRef}
              id="pdf-upload"
              type="file"
              accept=".pdf,application/pdf"
              onChange={handleFileSelect}
              className="bg-white border-amber-200 file:mr-4 file:py-1 file:px-3 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-amber-100 file:text-amber-700 hover:file:bg-amber-200"
            />
            {selectedFile && (
              <button
                onClick={handleClear}
                className="absolute right-2 top-1/2 -translate-y-1/2 p-1 hover:bg-amber-100 rounded"
              >
                <X className="w-4 h-4 text-amber-600" />
              </button>
            )}
          </div>
        </div>
        <Button
          onClick={handleLoadQuote}
          disabled={!selectedFile || isLoading}
          className="bg-amber-600 hover:bg-amber-700 text-white gap-2"
        >
          {isLoading ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Loading...
            </>
          ) : (
            <>
              <Upload className="w-4 h-4" />
              Load Quote to Edit
            </>
          )}
        </Button>
      </div>
      
      {selectedFile && (
        <p className="text-sm text-amber-600 mt-2">
          Selected: {selectedFile.name}
        </p>
      )}
    </div>
  );
}
